# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
#    - go mod tidy
#    - go mod vendor
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  ldflags:
    - -s -w -X info.Version={{.Version}} -X info.Commit={{.Commit}} -X info.Date={{ .CommitDate }} -X info.BuiltBy=goreleaser
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - mips64
    - mips64le
    - mips
    - mipsle
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: darwin
      goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: OpenIoTHub
      name: homebrew-tap
    folder: Formula
    homepage:  http://github.com/OpenIoTHub
    description: OpenIoTHub GateWay
    test: |
      system "#{bin}/gateway-go -v"
scoop:
  bucket:
    owner: OpenIoTHub
    name: scoop-bucket
  homepage:  http://github.com/OpenIoTHub
  description: OpenIoTHub GateWay
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage:  http://github.com/OpenIoTHub
    description: OpenIoTHub GateWay
    maintainer: OpenIoTHub <newfarry@126.com>
    license: MIT
    vendor: gateway-go
    formats:
      - deb
      - rpm
    scripts:
      preinstall: "scripts/install_remove/preinstall.sh"
      postinstall: "scripts/install_remove/postinstall.sh"
      preremove: "scripts/install_remove/preremove.sh"
      postremove: "scripts/install_remove/postremove.sh"
    contents:
      - src: systemd/**
        dst: /etc/systemd/system
      - src: gateway-go.yaml
        dst: /etc/gateway-go/gateway-go.yaml
        type: config
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    summary: OpenIoTHub GateWay.
    description: |
      OpenIoTHub GateWay
    grade: stable
    confinement: strict
#    confinement: classic
    publish: true
    apps:
      gateway-go:
        plugs: ["network", "network-bind"]
        daemon: simple
        command: gateway-go
dockers:
  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64

  - image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-armv7"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm
    goarm: 7

docker_manifests:
  - name_template: "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-arm64"
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-armv7"

  - name_template: "{{ .Env.DOCKER_USERNAME }}/gateway-go:latest"
    image_templates:
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-amd64"
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-arm64"
      - "{{ .Env.DOCKER_USERNAME }}/gateway-go:{{ .Tag }}-armv7"

  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"

  - name_template: "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:latest"
    image_templates:
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ tolower .Env.GITHUB_REPOSITORY }}:{{ .Tag }}-armv7"