language: go
go: 1.13.x
env:
- GO111MODULE=on
notifications:
  email:
    recipients:
    - newfarry@126.com
    on_success: always
addons:
  apt:
    packages:
    - snapcraft
services:
- docker
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=openiothub -p="$DOCKER_PASSWORD"
- test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
before_install:
- openssl aes-256-cbc -K $encrypted_219439784b94_key -iv $encrypted_219439784b94_iv
  -in snap.login.enc -out snap.login -d
