gatewayuuid: dc02370c-0834-4663-b8ad-5387111d228e
loginwithtokenlist: []
loginwithserverconf:
- connection_type: tcp
  last_id: 8ce2016c-7ecd-4edf-9cea-83e073cc0c7e
  server:
    server_host: 127.0.0.1
    tcp_port: 34320
    kcp_port: 34320
    udp_p2p_port: 34321
    kcp_p2p_port: 34322
    tls_port: 34321
    grpc_port: 34322
    login_key: HLLdsa544&*S
