common:
  id: 26a0bbb4-4d13-4ca6-a625-74e14229191e
  register_host: s1.365hour.com
lasttoken:
  client_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyaWQiOiIyNmEwYmJiNC00ZDEzLTRjYTYtYTYyNS03NGUxNDIyOTE5MWUiLCJoc3QiOiJzMS4zNjVob3VyLmNvbSIsInRjcHQiOjM0MzIwLCJrY3B0IjozNDMyMCwidGxzcCI6MzQzMjEsInAycHQiOjM0MzIxLCJwbSI6MSwiZXhwIjoyMDE1NTQzNjYzODcsIm5iZiI6MTU1NDM2NjM4N30.lpfkhOHeq4fYIIVoVZJwAzTxa2oMy-b9UaSJxdbAvgM
  explorer_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyaWQiOiIyNmEwYmJiNC00ZDEzLTRjYTYtYTYyNS03NGUxNDIyOTE5MWUiLCJoc3QiOiJzMS4zNjVob3VyLmNvbSIsInRjcHQiOjM0MzIwLCJrY3B0IjozNDMyMCwidGxzcCI6MzQzMjEsInAycHQiOjM0MzIxLCJwbSI6MiwiZXhwIjoyMDE1NTQzNjYzODcsIm5iZiI6MTU1NDM2NjM4N30.dmCcBTlxOkoxfQm-VPwn6VECzv_7UILte3iEofDN-Xs
