name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    if: github.repository == 'OpenIoTHub/gateway-go'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/gateway-go
          short-description: ${{ github.event.repository.description }}
