name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Test golang code
        run: go test ./...
      - name: Build golang code
        run: go build
  linux-android-windows-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: true
      - name: Install requirement
        run: sudo apt-get update && sudo apt-get install gcc-aarch64-linux-gnu binutils-mingw-w64 gcc-mingw-w64-x86-64 -y
      - name: Test golang code
        run: go test ./...
      - name: Build linux libs
        run: ./lib/buildso.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Build windows libs
        run: ./lib/builddll.sh
      - uses: actions/upload-artifact@v3
        with:
          name: linux-libs
          path: build/linux
      - uses: actions/upload-artifact@v3
        with:
          name: android-libs
          path: build/android
      - uses: actions/upload-artifact@v3
        with:
          name: windows-libs
          path: build/windows
  macos-iOS-libs:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Test golang code
        run: go test ./...
      - name: Build libs
        run: ./lib/builddylib.sh
      - uses: actions/upload-artifact@v3
        with:
          name: macos-libs
          path: build/macos
      - uses: actions/upload-artifact@v3
        with:
          name: ios-libs
          path: build/ios